//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EMS Test.rc
//
#define IDC_MYICON                      2
#define IDC_EMSTEST                     3
#define IDS_APP_TITLE                   101
#define IDD_ENTERCONFIGTEST             131
#define IDD_ENTERCONFIGAMP              132
#define IDD_EMSTEST_DIALOG              201
#define IDD_ABOUTBOX                    202
#define IDD_WANTTOEXIT                  203
#define IDD_PLACESENSOR                 204
#define IDD_SWITCHONSMHURV5             205
#define IDD_STARTAMP                    206
#define IDD_FINISHAMP                   207
#define IDD_SWITCHONHP                  208
#define IDD_PLACEEUT                    209
#define IDD_ERRORFILEAMP                210
#define IDD_SWITCHONHPAFG               211
#define IDD_USEDAMPS                    212
#define IDD_EXCEEDEDVOLTAGE             213
#define IDD_ENTERCONFIGURATION          214
#define IDD_INSTRUCTION                 215
#define IDD_SAVEFILE                    216
#define IDD_NEWFILE						217
#define IDM_ABOUT                       301
#define IDM_EXIT                        302
#define IDI_EMSTEST                     401
#define IDI_SMALL                       402
#define IDR_MAINFRAME                   501
#define ID_FILE_NEW                     601
#define ID_FILE_OPEN                    602
#define ID_FILE_SAVE                    603
#define ID_FILE_SAVEAS                  604
#define ID_FILE_EXIT                    605
#define ID_RUN_MEASUREMENT              606
#define ID_RUN_TEST                     607
#define ID_VIEW_GRAPHS                  608
#define ID_GRAPHS_ELECTRICFIELD         609
#define ID_GRAPHS_VOLTAGE               610
#define ID_VIEW_REPORT                  611
#define ID_REPORT_NEW                   612
#define ID_REPORT_OPEN                  613
#define ID_HELP_ABOUT                   614
#define ID_RUN                          614
#define ID_HELP_MANUAL                  615
#define ID_CONFIGAMP                    616
#define IDC_MODULATION                  1001
#define IDC_INITIALFREQ                 1002
#define IDC_FINALFREQ                   1003
#define IDC_FIELDEUT                    1004
#define IDC_MODULATIONFREQ              1005
#define IDC_MODULATION2                 1006
#define IDC_MODULATION3                 1007
#define IDC_MODULATION4                 1008
#define IDC_INITIALFREQ2                1009
#define IDC_FINALFREQ2                  1010
#define IDC_FIELDEUT2                   1011
#define IDC_MODULATION5                 1012
#define IDC_MODULATION6                 1013
#define IDC_MODULATION7                 1014
#define IDC_TAB1                        1015
#define IDC_MODULATION8                 1016
#define IDC_COMBO1                      1017
#define IDC_INITIALFREQ3                1018
#define IDC_HZ                          1019
#define IDC_FINALFREQ3                  1021
#define IDC_KHZ                         1022
#define IDC_EDIT1                       1022
#define IDC_FIELDEUT3                   1023
#define IDC_BUTTON1                     1023
#define IDC_MHZ                         1024
#define IDC_MODULATION9                 1025
#define IDC_GHZ                         1026
#define IDC_MODULATION10                1027
#define IDC_AMP1                        1028
#define IDC_MODULATION11                1029
#define IDC_LIST1                       1030
#define IDC_MODULATION12                1031
#define IDC_AMPNAME1                    1032
#define IDC_AMPNAME2                    1033
#define IDC_AMPNAME3                    1034
#define IDC_AMPNAME4                    1035
#define IDC_AMPNAME5                    1036
#define IDC_AMPNAME6                    1037
#define IDC_AMPNAME7                    1038
#define IDC_MINFREQAMP1                 1039
#define IDC_MINFREQAMP2                 1040
#define IDC_MINFREQAMP3                 1041
#define IDC_MINFREQAMP4                 1042
#define IDC_MINFREQAMP5                 1043
#define IDC_MINFREQAMP6                 1044
#define IDC_MINFREQAMP7                 1045
#define IDC_MAXFREQAMP1                 1046
#define IDC_MAXFREQAMP2                 1047
#define IDC_MAXFREQAMP3                 1048
#define IDC_MAXFREQAMP4                 1049
#define IDC_MAXFREQAMP5                 1050
#define IDC_MAXFREQAMP6                 1051
#define IDC_MAXFREQAMP7                 1052
#define IDC_MAXVOLTAMP1                 1056
#define IDC_MAXVOLTAMP2                 1057
#define IDC_MAXVOLTAMP3                 1058
#define IDC_MAXVOLTAMP4                 1060
#define IDC_MAXFREQAMP8                 1061
#define IDC_MAXVOLTAMP5                 1062
#define IDC_MAXFREQAMP9                 1063
#define IDC_MAXVOLTAMP6                 1064
#define IDC_MAXFREQAMP10                1065
#define IDC_MAXVOLTAMP7                 1066
#define IDC_MAXFREQAMP11                1067
#define IDC_MAXFREQAMP12                1068
#define IDC_MAXFREQAMP13                1069
#define IDC_MAXFREQAMP14                1070
#define IDC_FILENAME					1071
#define IDC_CANCELSAVE					1072
#define IDC_NEWFILENAME					1073
#define IDC_CANCELNEW					1074
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
